# Generated by Django 2.2.6 on 2019-11-14 20:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('author_name', models.CharField(max_length=1024)),
                ('author_surname', models.CharField(blank=True, max_length=1024)),
                ('publisher_name', models.CharField(max_length=1024)),
                ('publisher_city', models.CharField(blank=True, max_length=1024)),
                ('year_published', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ISBN', models.CharField(blank=True, max_length=1024)),
                ('category', models.CharField(choices=[('PW', 'Novel'), ('KP', 'Polish classics'), ('KZ', 'Foreign classics'), ('RZ', 'Different'), ('HS', 'History'), ('BG', 'Biography'), ('DZ', 'children/youth'), ('PZ', 'Poetry'), ('DVD', 'DVD'), ('AL', 'Albums'), ('RL', 'Religion')], max_length=1024)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BORROWED', 'Borrowed'), ('MISSING', 'Missing'), ('UNKNOWN', 'Unknown'), ('MAINTENANCE', 'Maintenance'), ('NONAVAILABLE', 'Non available')], max_length=1024)),
                ('location', models.CharField(blank=True, max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('arrival_date', models.DateField(default=datetime.date.today)),
                ('dismiss_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(default='Polish', max_length=1024)),
            ],
            options={
                'ordering': ['pk', 'author_surname'],
                'verbose_name_plural': 'Books',
                'verbose_name': 'Book',
            },
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('surname', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('READER', 'Reader')], max_length=1024)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=1024)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=1024)),
                ('number_of_incidences', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowing_date', models.DateField()),
                ('borrowing_return_date', models.DateField()),
                ('renewed_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField()),
                ('state', models.CharField(choices=[('BORROWED', 'Borrowed'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('RENEWED', 'Renewed'), ('INCIDENCE', 'Incidence')], max_length=1024)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblio.Book')),
                ('library_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblio.LibraryUser')),
            ],
        ),
    ]
